### ISSUE TITLE
2.3 availability

### ISSUE THREAD

**Issue by dzineit** [google/mug#11]
Hi, and thanks for this library - I've had a lot of use out of BiStream in particular.

There seem to be quite a few changes (I'm most interested in BiCollectors) which aren't in 2.2, and there don't seem to be any 2.3-SNAPSHOT versions in any snapshot repository, so just wondering whether this will change soon? Thanks, and apologies if I'm missing something here.

**Comment by fluentfuture** [comment]
Hi Oliver.

Thanks for the interest in BiStream.

As you've noted, there have been quite some API changes and new additions
as a result of internal discussions.

I've however been having trouble with the maven javadoc plugin, preventing
me from creating a new release. I did some research but found no workaround.

If anyone know what's going on with Maven javadoc, I'd be grateful for help!


[*ERROR*] Failed to execute goal
org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar *(default)* on
project mug: *MavenReportException: Error while creating archive: *

[*ERROR*] *Exit code: 1 - javadoc: error - The code being documented uses
modules but the packages defined in
http://docs.oracle.com/javase/7/docs/api/
<http://docs.oracle.com/javase/7/docs/api/> are in the unnamed module.*

**Comment by fluentfuture** [comment]
Never mind. I found that it can be fixed by upgrading to a later version of
Maven javadoc plugin.

Created release 3.0.

Please let me know if this release works for your use cases.

Thanks!

**Comment by dzineit** [comment]
Fantastic, thanks for the update - I'm on holiday currently but when I'm back I'll test it out!

**Comment by dzineit** [comment]
Seems to be working fine, currently struggling with trying to make my own BiCollectors beyond just toMap but pretty sure that's more my own lack of understanding! Thanks for this :)

**Comment by fluentfuture** [comment]
Hi, do you know that you can method reference Collector's as a BiCollector?

For example if you use Guava, collecting to an ImmutableMap is:

.collect(ImmutableMap::toImmutableMap);


Collecting to ImmutableListMultimap is:

.collect(ImmutableListMultimap::toImmutableListMultimap);


Internally we did need to create a few extra BiCollector implementations
for ones that need more than the key and value functions, such as
toImmutableSortedMap().

**Comment by dzineit** [comment]
Yes, my problem is with the Maps from Trove (e.g. TIntObjectHashMap) and BSON (BasicBSONObject, which is a Map<String, Object>) - they don't come with a Collector method to use. I'm sure I'll figure it out though I just need to find some time to look into it in proper detail!

**Comment by fluentfuture** [comment]
For that, the least amount of effort I can think of is to use
Collectors.collectingAndThen().

static <T> Collector<T, V, TIntObjectHashMap<V>> toIntObjectHashMap(
    Function<? super T, Integer> toInt, Function<? super T, ? extends V>
toValue) {
  return collectingAndThen(Collectors.toMap(toInt, toValue), m -> {
    TIntObjectHashMap<V> result = new TIntObjectHashMap<>();
    result.putAll(m);
    return result;
  };
}


Then you can use it in a Stream chain, or a BiStream chain with method
reference.

**Comment by dzineit** [comment]
Brilliant, that's exactly what I've been trying to achieve and is easily adaptable to the BasicBSONObject case as well - thanks very much!

**Comment by fluentfuture** [comment]
Note that this is relatively easy, but not the most efficient because it
needs to copy.

If you'd rather collect "in-place", you'd need to create custom Collector
using Collector.of(), like:

   return Collector
<https://cs.corp.google.com/piper///depot/google3/third_party/java_src/jdk/openjdk8/u60/trunk/jdk/src/share/classes/java/util/stream/Collector.java?l=197&ct=xref_jump_to_def&gsn=Collector&rcl=255705812>.of
<https://cs.corp.google.com/piper///depot/google3/third_party/java_src/jdk/openjdk8/u60/trunk/jdk/src/share/classes/java/util/stream/Collector.java?l=291&ct=xref_jump_to_def&gsn=of&rcl=255705812>(
       TIntObjectHashMap::new,        (m, input
<https://cs.corp.google.com/piper///depot/google3/java/com/google/common/labs/collect/BiStream.java?l=830&gs=kythe%253A%252F%252Fgoogle3%253Flang%253Djava%253Fpath%253Dcom.google.common.labs.collect.BiStream%25235b8d0a866108f442918231d36155c0358b2e179c7e9f12d04fb1083d214d8c52&gsn=input&ct=xref_usages>)
-> {          m.put(toInt.apply(input), toValue.apply(input));
},        (m1, m2) -> {
          TIntObjectHashMap<V> result = new TIntObjectHashMap<>();
          result.putAll(m1);
          result.putAll(m2);          return result;        },
identity());
